### ISSUE TITLE
Квесты не полные и местами глючат, ведут не к тем зданиям например.

### ISSUE THREAD

**Issue by alexandrage** [Grayzer/Empyrion#1]
Квесты не полные и местами глючат, ведут не к тем зданиям например.

**Comment by Grayzer** [comment]
это проблема с ключами разработчиков. когда они свои ключи не добавляют в файл *.yaml
т.е. новые ключи в самом переводе есть, а в игре - они не используются. вместо них остались старые.
тут я ничего сделать просто не смогу, т.к. вообще нет доступа к таким файлам. только к переводам есть.

сейчас, по идее, должно уже быть исправлено.
